### ISSUE TITLE
package.json parse error

### ISSUE THREAD

**Issue by vchaudha117** [dreamerslab/jquery.actual#20]
Package.json has a trailing ',' which leads to build fail
"contributors": [
    { "name": "Ben Lin", "email": "ben@dreamerslab.com" },
    { "name": "Erwin Derksen" },
    { "name": "Jon Tara", "email": "jtara-github-public@spamex.com" },
    { "name": "Matt Hinchliffe", "email": "matt@maketea.co.uk" },
    { "name": "Ryan Millikin" },
    { "name": "Jacob Quant" },
    { "name": "ejn" },
    { "name": "Rudolf", "email": "qa.kovalyov@gmail.com" },
  ],

**Comment by qakovalyov** [comment]
@vchaudha117. Firstly this package registered only for bower. But you can upload throught node if type link to repo. Just try update node and npm

**Comment by vchaudha117** [comment]
Works now. Thanks.

**Comment by ben-lin** [comment]
Fixed.
